<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>540f9e6a-41ba-4d42-a50d-a4989a2ce89e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LoanDecisionApi.Tests/**" />
    <Content Remove="LoanDecisionApi.Tests/**" />
    <None Remove="LoanDecisionApi.Tests/**" />
    <EmbeddedResource Remove="LoanDecisionApi.Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LoanDecisionApi.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.11" />
  </ItemGroup>

</Project>
